on: [push, pull_request]
name: Clippy check
jobs:
  clippy-check-arm:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv8m.main-none-eabihf
          components: clippy
      - run: cargo clippy --target=thumbv8m.main-none-eabihf
  clippy-check-riscv:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: riscv32imac-unknown-none-elf
          components: clippy
      - run: cargo clippy --target=riscv32imac-unknown-none-elf
