on: [push, pull_request]
name: Run update.sh and check for changed files
jobs:
  update-and-diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: ./update.sh
      - run: git diff --exit-code
